name: Docker Build & Push


on:
  push:
    branches:
      - main
      - initial

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #Added docker creds in github repo settings
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push to DockerHub
        working-directory: eks_project/docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-custom:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-custom:latest

