name: Deploy with Helm

on:
  workflow_dispatch:  # allows manual triggering from the GitHub UI
    inputs: #inputs should be given while triggering manually from githubactions
      cluster_name:
        description: Name of the EKS cluster
        required: true
      region:
        description: AWS region to deploy to
        required: true    
jobs:
  helm-deployment-eks:
    name: helm deployment to EKS cluster 
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: configuring AWS credentials # passed as secrets from repo
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Update kubeconfig for EKS Cluster # updates kube config from runner using aws keys/
        run: |
          aws eks update-kubeconfig --name ${{ github.event.inputs.cluster_name }} --region ${{ github.event.inputs.region }}

      - name: Install Helm CLI
        uses: azure/setup-helm@v3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install nginx-app ./eks_project/helm \
            --namespace default \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/nginx-custom \
            --set image.tag=latest
